### PR TITLE
ox on top

### PR DESCRIPTION
**Pull request by StrixLuca**

### CODE REVIEW

**Comment by Alivemonstor** [comment]
very informative thank you

**Comment by StrixLuca** [comment]
only need testing ahah

**Comment by Alivemonstor** [comment]
this isnt being merged btw not just gonna allow it only for ox

**Comment by StrixLuca** [comment]
uhm the script need ox_lib? 
for showTextUI 
why not full ox_lib

**Comment by StrixLuca** [comment]
and cache.ped 
people need ox_lib!!
cache.ped is better

**Comment by Alivemonstor** [comment]
ill make it both :)

**Pull request closed without merging**
